=== Ametys/runtime/docs/schemas/runtime.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--+
    | Copyright (c) 2007 Anyware Technologies and others.
    | All rights reserved. This program and the accompanying materials
    | are made available under the terms of the Eclipse Public License v1.0
    | which accompanies this distribution, and is available at
    | http://www.opensource.org/licenses/eclipse-1.0.php
    | 
    | Contributors:
    |     Anyware Technologies - initial API and implementation
    +-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="runtime" type="runtime">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">
                <![CDATA[
                    This is the root element of the runtime file.
                ]]>
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="runtime">
        <xsd:all>
            <xsd:element name="application" type="application">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This unique element declares information about the current application.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="initClass" maxOccurs="1" minOccurs="0" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This optional single element referes to a class that will be called once the initialisation of the application is over.<br/>
                            The class is an avalon component that must inherit org.ametys.runtime.plugin.Init
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="incompleteConfig" type="config">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element explains the behavior of a starting application that is not configured.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="plugins" type="plugins" maxOccurs="1" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element starts the section of the configuration of the plugins engine.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="workspaces" type="workspaces" maxOccurs="1" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element starts the configuration of the workspaces engine.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="extensions" type="extensions" maxOccurs="1" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element starts the section to choose the implementation for the single extension points.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="application">
        <xsd:all>
            <xsd:element name="version" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element declares the version of the current application (e.g. '1.0.0').<br/>
                            You can get this value using org.ametys.runtime.servlet.RuntimeConfig.getInstance().getApplicationVersion()
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="date" type="xsd:string" maxOccurs="1" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element declares the date of the release of the current application. The format is yyyyMMdd'T'HHmm (e.g. 20070601T1530 for the 1st of june 2007 at 3:30pm)<br/>
                            You can get this value using org.ametys.runtime.servlet.RuntimeConfig.getInstance().getApplicationBuildDate()
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="extensions">
	   <xsd:sequence>
            <xsd:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="workspaces">
        <xsd:all>
            <xsd:element name="exclude" type="excludedWorkspace" maxOccurs="1" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element describes workspace to disable.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:all>
        <xsd:attribute name="default" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation xml:lang="en">
                    <![CDATA[
                        This attribute defines the workspace to use by default.<br/>
                        A such workspace have a direct uri (without the '_'). 
                    ]]>
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>        
    </xsd:complexType>
    
    <xsd:complexType name="plugins">
        <xsd:all>
            <xsd:element name="exclude" type="excludedFeatures" maxOccurs="1" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element describes features of plugins to disable.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="locations" type="pluginsLocations" maxOccurs="1" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element discribe the list of locations for plugins families.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="excludedWorkspace">
        <xsd:sequence>
            <xsd:element name="workspace" type="xsd:string" maxOccurs="unbounded" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element defines as a text the name of a workspace to disable.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="excludedFeatures">
        <xsd:sequence>
            <xsd:element name="feature" type="xsd:string" maxOccurs="unbounded" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element contains as a text the full name of a feature that will be disabled.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="pluginsLocations">
        <xsd:sequence>
            <xsd:element name="location" type="xsd:string" maxOccurs="unbounded" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element contains as a text the name of a directory where to look for plugins, in addition to the default 'plugins' directory.<br/>
                            The directory is relative to the webapp.<br/>
                            The behavior of the runtime is exaclty the same if plugins are defined in different famillies or in the same one.<br/>
                            The only interrest in defining plugins in different families is to classify them.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="config">
        <xsd:all>
            <xsd:element name="redirectURL" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element contains as a text the internal url where to redirect when the application is started incompletly.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="allowedURLs" type="allowedURLs">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element contains the list of authorized urls when the application is started incompletly.<br/>
                            Resources url and configuration view url must be part of it.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="allowedURLs">
        <xsd:sequence>
            <xsd:element name="allowedURL" type="xsd:string" maxOccurs="unbounded" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation xml:lang="en">
                        <![CDATA[
                            This element contains as a text an url of an authorized url that will be handled even if the application configuration is not complete.<br/>
                            Be careful to test this url in these case because when the application is not started correctly most of the components are not started.
                        ]]>
                    </xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Ametys/runtime/test/environments/runtimes/runtime6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Copyright 2009 Anyware Services

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
   -->

<!-- 
    Init class needed for test
    Use the JDBC CredentialAware Modifiable User manager
-->
<runtime xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="http://ametys.org/Runtime/1.2/runtime.xsd">
    
    <application>
        <version>2.0.1</version>
        <date>20070115T2215 GMT</date>
    </application>
    
    <initClass>org.ametys.runtime.test.Init</initClass>
    
    <incompleteConfig>
        <allowedURLs>
            <allowedURL>_admin/public</allowedURL>
        	<allowedURL>_admin/resources</allowedURL>
        	<allowedURL>_admin/_plugins/core/administrator/config</allowedURL>
        	<allowedURL>_admin/plugins/core/administrator/config</allowedURL>
        </allowedURLs>
        <redirectURL>cocoon://_admin/public/load-config.html?uri=core/administrator/config/edit.html</redirectURL>
    </incompleteConfig>
    
    <plugins>
        <exclude>
            <feature>test</feature>
        </exclude>
        <locations>
            <location>test</location>
        </locations>
    </plugins>
    
    <workspaces default="myworkspace">
        <exclude>
            <workspace>test</workspace>
        </exclude>
    </workspaces>
    
    <extensions>
        <org.ametys.runtime.right.RightsManager>org.ametys.runtime.plugins.core.right.DefaultProfileBased</org.ametys.runtime.right.RightsManager>
        <org.ametys.runtime.exception.ExceptionHandler>org.ametys.runtime.plugins.core.exception.Default</org.ametys.runtime.exception.ExceptionHandler>
        <org.ametys.runtime.group.GroupsManager>org.ametys.runtime.plugins.core.group.Empty</org.ametys.runtime.group.GroupsManager>
        <org.ametys.runtime.authentication.CredentialsProvider>org.ametys.runtime.plugins.core.authentication.Basic</org.ametys.runtime.authentication.CredentialsProvider>
        <org.ametys.runtime.user.UsersManager>org.ametys.runtime.plugins.core.user.CoreModifiableCredentialsAwareJdbc</org.ametys.runtime.user.UsersManager>
    </extensions>
</runtime>

=== Ametys/runtime/test/environments/runtimes/runtime11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Location needed for test
-->
<runtime  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:noNamespaceSchemaLocation="http://ametys.org/Runtime/1.0/runtime.xsd">
    
    <application>
        <version>2.0.1</version>
    </application>
    
    <initClass>org.ametys.runtime.test.Init</initClass>
    
    <plugins>
        <locations>
            <location>location2</location>
        </locations>
    </plugins>
    
    <incompleteConfig>
        <allowedURLs/>
        <redirectURL/>
    </incompleteConfig>
    
    <extensions>
        <sep-test2>org.ametys.runtime.test.Default2</sep-test2>
    </extensions>
</runtime>

=== Ametys/runtime/test/environments/runtimes/runtime3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
   Copyright 2009 Anyware Services

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
   -->

<!-- 
    Init class needed for test
    Minimal runtime that use default extensions and no db
-->
<runtime xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="http://ametys.org/Runtime/1.2/runtime.xsd">
    
    <application>
        <version>2.0.1</version>
    </application>
    
    <initClass>org.ametys.runtime.test.Init</initClass>
    
    <plugins>
        <exclude>
            <feature>core/runtime.datasource.core</feature>
            <feature>core/runtime.upload</feature>
        </exclude>
    </plugins>
    
    <incompleteConfig>
        <allowedURLs/>
        <redirectURL/>
    </incompleteConfig>
    
    <extensions>
    	<org.ametys.runtime.plugins.core.userpref.UserPreferencesManager>org.ametys.runtime.plugins.core.userpref.EmptyUserPreferencesManager</org.ametys.runtime.plugins.core.userpref.UserPreferencesManager>
    </extensions>
</runtime>

=== Ametys/runtime/1.1/test/environments/runtimes/runtime10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Location needed for test
-->
<runtime  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:noNamespaceSchemaLocation="http://ametys.org/Runtime/1.0/runtime.xsd">
    
    <application>
        <version>2.0.1</version>
    </application>
    
    <plugins>
        <locations>
            <location>location1</location>
        </locations>
    </plugins>
    
    <incompleteConfig>
        <allowedURLs/>
        <redirectURL/>
    </incompleteConfig>
</runtime>
